#!/bin/sh
# Source this to revert to lowdpi settings

# Scale GTK icons and other UI elements
export GDK_SCALE=1.0
# Un-scale text (setting DPI in .Xresources_dpi)
export GDK_DPI_SCALE=1.0
# QT to use screen DPI
export QT_AUTO_SCREEN_SCALE_FACTOR=1
