#!/bin/sh
# You can run manually `git ctags` in a repository too
# YCM requires the --fields=+l in ctags
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --fields=+l
mv "$dir/$$.tags" "$dir/tags"

